// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkSUIlpEEjwnhX9fCTllazjmuwe3-SLto',
    appId: '1:383995815794:web:96ce2830205516700fdfeb',
    messagingSenderId: '383995815794',
    projectId: 'habit-tracker-app-a7e53',
    authDomain: 'habit-tracker-app-a7e53.firebaseapp.com',
    storageBucket: 'habit-tracker-app-a7e53.firebasestorage.app',
    measurementId: 'G-DBFGR5ZJ5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgrNCZIe-PVTh2i73Qf0ZjykWjFrGJhZo',
    appId: '1:383995815794:android:2098cf0fff9f8ddd0fdfeb',
    messagingSenderId: '383995815794',
    projectId: 'habit-tracker-app-a7e53',
    storageBucket: 'habit-tracker-app-a7e53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXDTvXaDxjAaRjTOx9XAsWaxyRfteK8Gc',
    appId: '1:383995815794:ios:f171355df22991180fdfeb',
    messagingSenderId: '383995815794',
    projectId: 'habit-tracker-app-a7e53',
    storageBucket: 'habit-tracker-app-a7e53.firebasestorage.app',
    iosBundleId: 'com.example.habitTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXDTvXaDxjAaRjTOx9XAsWaxyRfteK8Gc',
    appId: '1:383995815794:ios:f171355df22991180fdfeb',
    messagingSenderId: '383995815794',
    projectId: 'habit-tracker-app-a7e53',
    storageBucket: 'habit-tracker-app-a7e53.firebasestorage.app',
    iosBundleId: 'com.example.habitTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkSUIlpEEjwnhX9fCTllazjmuwe3-SLto',
    appId: '1:383995815794:web:0f859632531ba3780fdfeb',
    messagingSenderId: '383995815794',
    projectId: 'habit-tracker-app-a7e53',
    authDomain: 'habit-tracker-app-a7e53.firebaseapp.com',
    storageBucket: 'habit-tracker-app-a7e53.firebasestorage.app',
    measurementId: 'G-Y7X5J2JXZC',
  );

}